version: 2

updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    groups:
      gradle-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: gomod
    directory: "/services/preferred-video"
    schedule:
      interval: weekly
      day: monday
      time: "04:15"
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    groups:
      go-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: "/services/preferred-video"
    schedule:
      interval: weekly
      day: monday
      time: "04:30"
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    groups:
      docker-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "04:45"
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    groups:
      actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
